
include: package:flutter_lints/flutter.yaml

linter:
  rules:

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "lib/constants/enums/env_key.dart"
  errors:
    invalid_annotation_target: ignore