name: be_sharp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.19+19

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  auto_route: ^10.1.0+1
  cloud_firestore: ^5.6.11 
  cloud_functions: ^5.6.1 
  collection: ^1.19.1 
  cupertino_icons: ^1.0.8 
  firebase_auth: ^5.6.2 
  firebase_core: 
  firebase_crashlytics: 
  firebase_messaging: ^15.2.9 
  firebase_remote_config: ^5.4.7 
  flutter_dotenv: ^5.2.1 
  flutter_flavor: ^3.1.4 
  flutter_flavorizr: 
  flutter_hooks: ^0.21.2 
  flutter_riverpod: ^2.6.1 
  fluttertoast: ^8.2.12 
  font_awesome_flutter: ^10.8.0 
  freezed_annotation: ^3.1.0 
  google_fonts: ^6.2.1 
  google_sign_in: ^7.1.0 
  gpt_markdown: ^1.1.1 
  hooks_riverpod: ^2.6.1 
  image: ^4.5.4 
  image_cropper: ^9.1.0 
  image_picker: ^1.1.2 
  in_app_purchase: ^3.2.3 
  in_app_purchase_android: ^0.4.0+2 
  in_app_purchase_storekit: ^0.4.2 
  in_app_review: ^2.0.10 
  path_provider: ^2.1.5 
  riverpod_annotation: ^2.6.1 
  shared_preferences: ^2.5.3 
  sign_in_with_apple: ^7.0.1 
  ulid: ^2.0.1 
  url_launcher: ^6.3.1 

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^10.2.3
  build_runner: ^2.5.4 
  flutter_launcher_icons: ^0.14.4 
  flutter_lints: ^6.0.0 
  freezed: ^3.1.0 
  json_serializable: ^6.9.5 
  riverpod_generator: ^2.6.5 
  riverpod_lint: ^2.6.5 
flutter:
  uses-material-design: true

  assets:
    - assets/env/
    - assets/images/
flavorizr:
  app:
    android:
      flavorDimensions: "flavor-type"
  flavors:
    dev:
      app:
        name: "BeSharp. DEV"
      android:
        applicationId: "com.firebaseapp.be_sharp_dev"
      ios:
        bundleId: "com.firebaseapp.beSharpDev"
    stg:
      app:
        name: "BeSharp. STG"
      android:
        applicationId: "com.firebaseapp.be_sharp_stg"
      ios:
        bundleId: "com.firebaseapp.beSharpStg"
    prod:
      app:
        name: "BeSharp."
      android:
        applicationId: "com.firebaseapp.be_sharp_prod"
      ios:
        bundleId: "com.firebaseapp.beSharpProd"
flutter_icons:
  android: true
  ios: true