name: be_sharp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.17+17

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_flavor: ^3.1.3
  flutter_flavorizr: ^2.2.3
  firebase_core: ^3.4.0
  flutter_dotenv: ^5.2.1
  firebase_crashlytics: ^4.1.0
  firebase_messaging: ^15.2.4
  get: ^4.6.6
  flutter_riverpod: ^2.6.1
  cloud_firestore: ^5.4.0
  firebase_auth: ^5.2.0
  fluttertoast: ^8.2.8
  flutter_hooks: ^0.20.5
  firebase_remote_config: ^5.1.0
  google_sign_in: ^6.2.2
  freezed_annotation: ^2.4.4
  sign_in_with_apple: ^6.1.4
  shared_preferences: ^2.2.3
  image_picker: ^1.1.2
  image: ^4.3.0
  image_cropper: ^9.0.0
  path_provider: ^2.1.4
  cloud_functions: ^5.1.0
  ulid: ^2.0.1
  hooks_riverpod: ^2.6.1
  google_fonts: ^6.2.1
  lottie: ^3.1.3
  in_app_purchase: ^3.2.0
  in_app_purchase_android: ^0.3.6+7
  in_app_purchase_storekit: ^0.3.21
  font_awesome_flutter: ^10.8.0
  flutter_markdown_latex: ^0.3.4
  flutter_markdown: ^0.7.6+1
  markdown: ^7.3.0
  in_app_review: ^2.0.10
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.0
  flutter_launcher_icons: ^0.13.1
flutter:
  uses-material-design: true

  assets:
    - assets/env/
    - assets/images/
flavorizr:
  app:
    android:
      flavorDimensions: "flavor-type"
  flavors:
    dev:
      app:
        name: "BeSharp. DEV"
      android:
        applicationId: "com.firebaseapp.be_sharp_dev"
      ios:
        bundleId: "com.firebaseapp.beSharpDev"
    stg:
      app:
        name: "BeSharp. STG"
      android:
        applicationId: "com.firebaseapp.be_sharp_stg"
      ios:
        bundleId: "com.firebaseapp.beSharpStg"
    prod:
      app:
        name: "BeSharp."
      android:
        applicationId: "com.firebaseapp.be_sharp_prod"
      ios:
        bundleId: "com.firebaseapp.beSharpProd"
flutter_icons:
  android: true
  ios: true