name: be_sharp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_flavor: ^3.1.3
  flutter_flavorizr: ^2.2.3
  firebase_core: ^3.4.0
  flutter_dotenv: ^5.2.1
  firebase_crashlytics: ^4.1.0
  firebase_messaging: ^15.1.0
  get: ^4.6.6
  flutter_riverpod: ^2.6.1
  cloud_firestore: ^5.4.0
  firebase_auth: ^5.2.0
  fluttertoast: ^8.2.8
  flutter_hooks: ^0.20.5
  firebase_remote_config: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  flutter_launcher_icons: ^0.14.2
  freezed: ^2.5.2
  json_serializable: ^6.8.0
flutter:
  uses-material-design: true

  assets:
    - assets/env/
    - assets/images/
flavorizr:
  app:
    android:
      flavorDimensions: "flavor-type"
  flavors:
    dev:
      app:
        name: "BeSharp. DEV"
      android:
        applicationId: "com.firebaseapp.be_sharp_dev"
      ios:
        bundleId: "com.firebaseapp.beSharpDev"
    stg:
      app:
        name: "BeSharp. STG"
      android:
        applicationId: "com.firebaseapp.be_sharp_stg"
      ios:
        bundleId: "com.firebaseapp.beSharpStg"
    prod:
      app:
        name: "BeSharp."
      android:
        applicationId: "com.firebaseapp.be_sharp_prod"
      ios:
        bundleId: "com.firebaseapp.beSharpProd"
